
import 'dart:io';

// void main() {
  // Degrees and their corresponding branches
  Map<String, List<String>> degreeBranches = {
    "BBA": [
      "General Management",
      "Marketing Management",
      "Financial Management",
      "HR Management",
      "International Business",
      "Supply Chain Management",
      "Retail Management",
      "IT Management",
      "Entrepreneurship",
      "Hospitality Management"
    ],

    "B.Com": [
      "General",
      "Accounting and Finance",
      "Taxation",
      "Banking and Insurance",
      "Corporate Secretaryship",
      "Business Analytics",
      "Foreign Trade",
      "E-Commerce",
      "Advertising & Sales Management",
      "Computer Applications"
    ],

    "B.Tech": [
      "Computer Science (CSE)",
      "Information Technology (IT)",
      "Electronics and Communication(ECE)",
      "Mechanical Engineering (ME)",
      "Civil Engineering (CE)",
      "Data Science and Artificial Intelligence",
      "AI and ML",
      "Cyber Security",
      "IoT (Internet of Things)",
      "Software Engineering",
      "Electrical Engineering (EE)",
      "Electrical and Electronics (EEE)",
      "Aerospace Engineering",
      "Automobile Engineering",
      "Chemical Engineering",
      "Biomedical Engineering",
      "Biotechnology",
      "Agricultural Engineering",
      "Environmental Engineering",
      "Instrumentation Engineering",
      "Mining Engineering",
      "Petroleum Engineering",
      "Metallurgical Engineering",
      "Textile Engineering",
      "Production Engineering",
      "Marine Engineering",
      "Robotics Engineering",
      "Mechatronics Engineering",
      "Food Technology",
      "Plastic Technology"
    ],
    "Diploma": [
      "Mechanical Engineering",
      "Civil Engineering",
      "Electrical Engineering",
      "ECE",
      "Computer Science Engineering",
      "Automobile Engineering",
      "Information Technology",
      "Instrumentation Engineering",
      "Chemical Engineering",
      "Mining Engineering",
      "Architecture",
      "Fashion Designing",
      "Interior Designing",
      "Hotel Management",
      "Pharmacy",
      "Agricultural Engineering"
    ],
    "M.Com": [
      "General",
      "Accounting and Finance",
      "Banking and Finance",
      "Business Management",
      "Taxation",
      "E-Commerce",
      "Marketing",
      "HR Management",
      "International Business",
      "Computer Applications"
    ],
    "M.Sc": [
      "General",
      "Physics",
      "Chemistry",
      "Mathematics",
      "Biotechnology",
      "Botany",
      "Zoology",
      "Microbiology",
      "Environmental Science",
      "Computer Science",
      "Geology",
      "Agricultural Science",
      "Food Technology",
      "Forensic Science",
      "Nursing",
      "Psychology"
    ],

    "M.Tech": [
      "Structural Engineering",
      "CSE",
      "VLSI System Design",
      "Thermal Engineering",
      "Power Systems",
      "Environmental Engineering",
      "Chemical Engineering",
      "Instrumentation Engineering",
      "Electrical Engineering",
      "Power System Engineering",
      "Mechanical Engineering (ME)",
      "ECE",

    ],
    "MBA": [
      "Marketing ",
      "HR Management",
      "Finance",
      "Operations Management ",
      "Information Technology",
      "Tourism Management",
      "Business Analytics",
      "Healthcare Management",
      "International Business",
      "Entrepreneurship",
      "Media Management",
      "Hospitality Management",
      "Infrastructure Management",
      "Digital Marketing",
      "Education Management",
      "Textile Management",
      "Supply Chain Management",
      "Strategic Management",
      "Agri-Management",
      "Energy Management"

    ],
    "B.Sc": [
      "Physics",
      "Chemistry",
      "Mathematics",
      "Biology",
      "Computer Science",
      "Environmental Science",
      "Biotechnology",
      "Microbiology",
      "Botany",
      "Zoology",
      "Psychology",
      "Forensic Science",
      "Statistics",
      "Astronomy",
      "Geology",
      "Agricultural Science",
      "Nautical Science",
      "Fashion Designing",
      "Food Science",
      "Home Science",
      "Animation",
      "Genetics",
      "Sports Science"
    ],
    "BCA": [
      "Database Management Systems",
      "Web Development",
      "Networking",
      "Cloud Computing",
      "Mobile App Development",
      "Artificial Intelligence",
      "Cyber Security"
    ],
    "MCA": [
      "Computer Applications",
      "Information Technology",
      "Software Engineering",
      "Networking",
      "Data Science",
      "Artificial Intelligence",
      "Cyber Security",
      "Cloud Computing",
      "Mobile Development",
      "E-Commerce",
      "Database Management Systems"
    ],

    "BA": [
      "English",
      "History",
      "Political Science",
      "Economics",
      "Psychology",
      "Sociology",
      "Philosophy",
      "Geography"
    ]
  };

  // Welcome message

//}